# Generated by Django 5.1.3 on 2024-11-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Name of taks',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='describe task for solution',
        ),
        migrations.AddField(
            model_name='task',
            name='describe',
            field=models.TextField(default='DO IT', max_length=20000),
        ),
    ]
